apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.rabbitmq
  metadata:
  - name: host
    value: "localhost:5672" # Required. Example: "rabbitmq.default.svc.cluster.local:5672"
  - name: consumerID
    value: "61415901178272324029" # Required. Any unique ID. Example: "myConsumerID"
  - name: durable
    value: "true" # Optional. Default: "false"
  - name: deletedWhenUnused
    value: "false" # Optional. Default: "false"
  - name: autoAck
    value: "false" # Optional. Default: "false"
  - name: deliveryMode
    value: "2" # Optional. Default: "0". Values between 0 - 2.
  - name: requeueInFailure
    value: "true" # Optional. Default: "false".